### ISSUE TITLE
Problems with locations provider getCurrentPlace

### ISSUE THREAD

**Issue by kal27** [mcharmas/Android-ReactiveLocation#102]
Hi I'm trying to use ReactiveLocationProvider to get current place, whenever my gps is turned on but my wifi is turned off  I get IllegalStateException saying
...
rx.exceptions.OnErrorNotImplementedException
..
Caused by: java.lang.IllegalStateException
com.google.android.gms.common.internal.zzx.zzab(Unknown Source)
com.google.android.gms.common.data.zzc.zzbF(Unknown Source)

When trying to get placeLikelihood from placelikelihoodbuffer.

My code is pretty simple, it uses getCurrentPlace in a similar way as it's done in the sample code.

When i turn the wifi on and gps off i get server timed out error.

The library only works for me when both gps and wifi are turned on.

So is internet connection required for this library to work? I thought the gps, might be enough

I'm not sure whether this is an issue.

**Comment by mcharmas** [comment]
Hi,
first of wall this library is just a wrapper around GMS API. The IllegalStateException you see is thrown by GCM for some reason. You can check out if this exception is still thrown when you use GMS directly. This is not an issue of this library.

To learn if internet connection is required to obtain location (btw it should't be) please refer to Google Play Services docs.

To catch this exception and not let the application crash please handle the error passing second parameter (onError) to ```subscribe()``` function in the observable. More about handling errors in RxJava you can read on exceptional Rx docs: http://reactivex.io/
