### ISSUE TITLE
getLastKnownLocation does not emit if location is not known

### ISSUE THREAD

**Issue by djensen47** [mcharmas/Android-ReactiveLocation#103]
According to the docs for `getLastKnownLocation`: 

> Delivered location is never null - when it is unavailable Observable completes without emitting any value.

I have a stream where I'm getting the last known location, performing a flatMap which makes an API call, and emits a different observable.

The problem is that I always need to make the API call, even if the location is not or known. 

It would be nice to have an option that forces the API to return an observable that indicates an unknown location. By default the existing behavior would prevail.

For now I'm going to use `getUpdatedLocation` with a timeout, like in the example, and `take(1)`.

**Comment by djensen47** [comment]
Looks like in RxJava we have firstOrDefault, which also fixes my issue.

Maybe this is a non-isue.

**Comment by mcharmas** [comment]
RxJava is very flexible in this matter. You can also use [switchIfEmpty operator](http://reactivex.io/documentation/operators/defaultifempty.html)

**Comment by djensen47** [comment]
:ok_hand: :+1:
