### ISSUE TITLE
API for .requestLocationUpdates unnecessary complicated

### ISSUE THREAD

**Issue by martyglaubitz** [mcharmas/Android-ReactiveLocation#104]
The raw Google Play Services API alllows you to simply pass a callback to *FusedLocationApi.requestLocationUpdates* like so:

```java
_pendingResult = LocationServices.FusedLocationApi.requestLocationUpdates(googleApiClient, locationRequest, new LocationListener() {
    @Override
    public void onLocationChanged(final Location location) {
        // do whatever
    }
 })
```

why does the library API for this require shenanigans with PendingIntent?

**Comment by mcharmas** [comment]
This API should be added for sure but the way with PendingIntent is very useful and let's system kill your app and wake it up on next location update. This is used on long location updates intervals.

**Comment by martyglaubitz** [comment]
yes, but in most cases people are going to unsubscribe from location updates anyway when their fragmen/activity gets stopped. and for these cases you certainly don't want to dance around with PendingIntents

**Comment by mcharmas** [comment]
Sure thing.

**Comment by mcharmas** [comment]
I was going to implement this feature when I saw it is already there. Please use ```getUpdatedLocation```. It uses method you describe underneath.

**Comment by martyglaubitz** [comment]
@mcharmas i see... but the semantics of the method names suggest you to use *.requestLocationUpdates* when you want to subscribe to a stream of location updates. whereas *getUpdatedLocation* suggests you that you'll get only one update
