### ISSUE TITLE
How to make sure that the Location's Address is always in English?

### ISSUE THREAD

**Issue by boggogo** [mcharmas/Android-ReactiveLocation#106]
In my app I am using this great library to get location updates. After getting the location I am doing a reverse geocoding on it to optain the Address (for example "Aberdeen, UK"). My problem is that if the device's language is in let say bulgarian the string is in bulgarian as well (after pervorming the reverse geocoding). Any suggestions on how to force the Address to be in English only?

This is how I am doing the reverse geocoding:

`Observable<List<Address>> reverseGeocodeObservable;
String locationName = "";
....

 public void getLocationName(){
    reverseGeocodeObservable
            .subscribeOn(Schedulers.io())// use I/O thread to query for addresses
            .observeOn(AndroidSchedulers.mainThread())// return result in main android thread to manipulate UI
            .subscribe(new Subscriber<List<Address>>() {
                @Override
                public void onCompleted() {

                }

                @Override
                public void onError(Throwable e) {
                    Log.d(TAG,"OnError Geocode");
                    locationName = sharedPref.getString(getString(R.string.location_name_on_error),"unknown");
                }

                @Override
                public void onNext(List<Address> addresses) {
                    if(addresses.size() > 0) {
                        Address address = addresses.get(0);
                        Log.v(MainActivity.class.getSimpleName(),"Locality: "+address.getLocality() + ", CountryName " + address.getCountryName());
                        //check if cityName is null...
                        String cityName = "unknown";
                        if(address.getLocality() != null) {
                            cityName = address.getLocality();
                            //if it is, try to get the subAdmin Area instead...
                        }else if (address.getSubAdminArea() != null){
                            cityName = address.getSubAdminArea();
                        }
                        String countryName = address.getCountryName();
                        editor.putString(getString(R.string.location_name_on_error),cityName + ", " + countryName);
                        editor.apply();
                        locationName = getString(R.string.location_name, cityName, countryName);
                    }
                }
            });
}`

**Comment by alpercem70** [comment]
Geocoder uses Locale.getDefault() if you don't pass it explicitly. It might be better to set your Locale to English in your application class or activity rather than defining it on the library.

**Comment by boggogo** [comment]
Thank you for your suggestion. I will definitely try that! :)

**Comment by mcharmas** [comment]
I've added API to pass locales for reverse geocoding in 0.9. Check it out.

śr., 11.05.2016, 08:49 użytkownik Georgi Koemdzhiev <
notifications@github.com> napisał:

**Comment by boggogo** [comment]
Hi @mcharmas! Thanks, that's great! Definitely will check it out :)
