### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by AndreyGrowl** [mcharmas/Android-ReactiveLocation#108]
Hi. I'm trying to use pl.charmas.android:android-reactive-location:0.8@aar. Here's the result :

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 19 declared in library [com.samwolfand.oneprefs:one-prefs:1.0] C:\workspace\WeatherYoda\app\build\intermediates\exploded-aar\com.samwolfand.oneprefs\one-prefs\1.0\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.samwolfand.oneprefs" to force usage

how can it be fixed? Thanks

**Comment by cyrixmorten** [comment]
Looking at the output, it looks like you are using https://github.com/swolfand/OnePrefs, which has minSdkVersion set to 19 https://github.com/swolfand/OnePrefs/blob/master/oneprefs/build.gradle

So, from what I understand 1) Seemingly the error has nothing to do with this library 2) to fix, simply set minSdkVersion to 19 in your own build.gradle
