### ISSUE TITLE
NullPointer exception in sample

### ISSUE THREAD

**Issue by sytolk** [mcharmas/Android-ReactiveLocation#11]
Hi
Thanks for the great library. Can you change in sample LocationToStringFunc like this, to avoid null pointer exception if its running in emulator:

private static class LocationToStringFunc implements Func1<Location, String> {
        @Override
        public String call(Location location) {
            if (location != null)
                return location.getLatitude() + " " + location.getLongitude() + " (" + location.getAccuracy() + ")";
            return "no location available";
        }
    }

**Comment by sergiiz** [comment]
@LOG-TAG I've just faced with the same problem. Any workarounds available?
It seems to be an issue http://stackoverflow.com/questions/16119130/android-java-io-ioexception-service-not-available

**Comment by mcharmas** [comment]
This is internal Android error. To catch this you have to pass error handler in subscibe method. I don't know any workaround other then implementing geodecoding yourself as stated in 3rd answer of SO you linked. You can put it into observable as well.

**Comment by cyrixmorten** [comment]
I have made some example code to work around using HTTP in this SO: http://stackoverflow.com/questions/19059894/google-geocoder-service-is-unavaliable-coordinates-to-address/19061688#19061688 

Maybe something similar can be merged into this library in the future to counter `java.io.IOException: Service not Available`
