### ISSUE TITLE
Slow app compiling

### ISSUE THREAD

**Issue by AlirezaAkbarix** [mcharmas/Android-ReactiveLocation#110]
I have a simple app to work with RX having these libs:
`testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:design:23.3.0'
    compile 'com.google.android.gms:play-services-location:8.4.0'

```
compile 'io.reactivex:rxjava:1.1.5'
compile 'io.reactivex:rxandroid:1.2.0'
compile 'pl.charmas.android:android-reactive-location:0.9@aar'`
```

before adding this lib (`compile 'pl.charmas.android:android-reactive-location:0.9@aar'`) android studio had compiled app fast with no problem, but after adding this lib, compiling is too slow and CPU goes 100%! 

My CPU is Core-i7 3610
and also 8GB RAM

**Comment by mcharmas** [comment]
I know it's more then a year but I can't reproduce it.
