### ISSUE TITLE
show enable location dialog like google maps

### ISSUE THREAD

**Issue by kamilwlf** [mcharmas/Android-ReactiveLocation#115]
Is it implemented in the library?
![gps](https://cloud.githubusercontent.com/assets/7765963/15823582/9df23602-2bfb-11e6-82e2-efcc47b2104b.png)

**Comment by esafirm** [comment]
It is a part of GMS Location.
You can implement this by using `ReactiveLocationProvider.checkLocationSettings()` like this

```java
locationProvider.checkLocationSettings(
                new LocationSettingsRequest.Builder()
                        .addLocationRequest(getLocationRequest())
                        .setAlwaysShow(true)
                        .build()
```

**Comment by renegens** [comment]
Is the `getLocationRequest()` available in the library or should be from the GMS location?

**Comment by mcharmas** [comment]
I know it's nearly a year but ```getLocationRequest()``` is your method producing desired location request.
