### ISSUE TITLE
Detect fake gps

### ISSUE THREAD

**Issue by sibelius** [mcharmas/Android-ReactiveLocation#117]
How can I detect a fake gps using this library?

**Comment by cyrixmorten** [comment]
You can inspect the Location object

https://developer.android.com/reference/android/location/Location.html#isFromMockProvider()

2016-06-24 15:40 GMT+02:00 Sibelius Seraphini <notifications@github.com>:

**Comment by sibelius** [comment]
thanks

**Comment by sibelius** [comment]
@cyrixmorten how long do u think that would take to when I click in a button, I read gps information and check if the gps is fake or not?

**Comment by sibelius** [comment]
another problem is that isFromMockProvider is for min sdk > 18, I'm using min version of 15

**Comment by cyrixmorten** [comment]
I'm not sure what you mean to do.. If you request location updates without
setting it to mock mode, they will be valid Location updates.

The time it takes depends. However, even in poor visibility to satalites,
you should get a fused location update almost instantly (GSM, WiFi).

If your goal is to distinguish between whether or not the Location update
came from GPS or Network, then I believe you should be able to look for
whether or not certain information is available in the Location update. For
instance time, altitude, speed. Such information is only available for GPS
updates.
This checking of availability of data should be working for all sdk's.

2016-06-24 16:37 GMT+02:00 Sibelius Seraphini <notifications@github.com>:
