### ISSUE TITLE
Tthrow exception when Location permission is blocked (Android M)

### ISSUE THREAD

**Issue by metjka** [mcharmas/Android-ReactiveLocation#120]
I looks like when Library cant access LOCATION permission  it just calls onCompleted.

**Comment by gabrieloshiro** [comment]
Alternatively the method can use annotations from [support annotations library](http://tools.android.com/tech-docs/support-annotations)

```
@RequiresPermission(anyOf = {
    Manifest.permission.ACCESS_COARSE_LOCATION,
    Manifest.permission.ACCESS_FINE_LOCATION})
public abstract Location getLastKnownLocation(String provider);
```

So LINT can generate an error if the permission is missing from the manifest.

**Comment by shingz96** [comment]
But with this lint check, android studio will report error with not check permission, how can i pass this lint check?

**Comment by mcharmas** [comment]
@shingz96 you have to obtain permission before subscribing
