### ISSUE TITLE
proguard warning with play-service-location version 9.2.1

### ISSUE THREAD

**Issue by iam1492** [mcharmas/Android-ReactiveLocation#121]
When I use latest playservice library, my proguard showing warnings. (of course cannot build)
It is ok when using 9.0.2 of play-service-location

here is warnings
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider: can't find referenced class com.google.android.gms.location.places.Places
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider: can't find referenced class com.google.android.gms.location.places.Places
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider: can't find referenced class com.google.android.gms.location.places.Places
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider: can't find referenced class com.google.android.gms.location.places.PlaceFilter
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider: can't find referenced class com.google.android.gms.location.places.PlaceFilter
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider: can't find referenced class com.google.android.gms.location.places.PlaceFilter
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider: can't find referenced class com.google.android.gms.location.places.PlaceLikelihoodBuffer
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider: can't find referenced class com.google.android.gms.location.places.PlaceBuffer
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider: can't find referenced class com.google.android.gms.location.places.AutocompleteFilter
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider: can't find referenced class com.google.android.gms.location.places.AutocompleteFilter
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider: can't find referenced class com.google.android.gms.location.places.AutocompleteFilter
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider: can't find referenced class com.google.android.gms.location.places.AutocompletePredictionBuffer
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$2: can't find referenced class com.google.android.gms.location.places.Places
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$2: can't find referenced class com.google.android.gms.location.places.PlaceDetectionApi
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$2: can't find referenced class com.google.android.gms.location.places.Places
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$2: can't find referenced class com.google.android.gms.location.places.PlaceDetectionApi
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$2: can't find referenced class com.google.android.gms.location.places.PlaceFilter
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$2: can't find referenced class com.google.android.gms.location.places.PlaceFilter
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$2: can't find referenced class com.google.android.gms.location.places.PlaceLikelihoodBuffer
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$2: can't find referenced class com.google.android.gms.location.places.PlaceLikelihoodBuffer
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$3: can't find referenced class com.google.android.gms.location.places.Places
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$3: can't find referenced class com.google.android.gms.location.places.GeoDataApi
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$3: can't find referenced class com.google.android.gms.location.places.Places
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$3: can't find referenced class com.google.android.gms.location.places.GeoDataApi
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$3: can't find referenced class com.google.android.gms.location.places.PlaceBuffer
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$3: can't find referenced class com.google.android.gms.location.places.PlaceBuffer
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$4: can't find referenced class com.google.android.gms.location.places.Places
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$4: can't find referenced class com.google.android.gms.location.places.GeoDataApi
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$4: can't find referenced class com.google.android.gms.location.places.Places
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$4: can't find referenced class com.google.android.gms.location.places.GeoDataApi
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$4: can't find referenced class com.google.android.gms.location.places.AutocompleteFilter
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$4: can't find referenced class com.google.android.gms.location.places.AutocompleteFilter
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$4: can't find referenced class com.google.android.gms.location.places.AutocompletePredictionBuffer
Warning: pl.charmas.android.reactivelocation.ReactiveLocationProvider$4: can't find referenced class com.google.android.gms.location.places.AutocompletePredictionBuffer

**Comment by amayatsky** [comment]
You can't use this library with 9.2.0 since it is supporting 8.4.0 only.
Wait for a #119 to be merged or for another update from author.

**Comment by ruigoncalo** [comment]
@iam1492 are you calling `com.google.android.gms:play-services-maps`and `com.google.android.gms:play-services-places`?

**Comment by esafirm** [comment]
Any update on this one?

**Comment by ZahidRasheed** [comment]
Any update here?

**Comment by KennyGoers** [comment]
Honestly it has nothing to do with what library versions is supported by the author, these are proguard warnings, not Play Services issues. I've used this library with 9.6 without issue, it just doesn't have proguard settings...
