### ISSUE TITLE
Check setNumUpdates and send onComplete

### ISSUE THREAD

**Issue by BraisGabin** [mcharmas/Android-ReactiveLocation#124]
I think that `ReactiveLocationProvider.getUpdatedLocation()` must check `LocationRequest.getNumUpdates()` and set a `take()` with that number. To keep a stream open when it's not going to send more events doesn't have sense.

**Comment by sergbek** [comment]
it would be very nice

**Comment by mcharmas** [comment]
Duplicate of #149. Just fixed.
