### ISSUE TITLE
NetworkOnMainThread on retrofit all that follows getLastKnowLocation

### ISSUE THREAD

**Issue by KennyGoers** [mcharmas/Android-ReactiveLocation#133]
As a simplified example from an Activity
```
        new ReactiveLocationProvider(this).getLastKnownLocation()
            .singleOrDefault(null)
            .flatMap(new Func1<Location, Observable<List<OfferLocation>>>() {
                @Override
                public Observable<List<OfferLocation>> call(Location location) {
                        return ARetrofitAPI.getOfferLocations(offer.getId(), latLng);
                }
            })
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe();
```
getLastKnownLocation() works fine and then the RetroFit wrapper call, that works EVERYWHERE else, throws NetworkOnMainThreadException, I've tried both 0.9 and 0.10, when either are by themselves in separate subscriptions all is fine.

**Comment by mcharmas** [comment]
All location callbacks are performed on main thread. This is GMS specific.
You have three solutions to your problem:

- set Retrofit scheduler on your ```RxJavaCallAdapterFactory.create()```
- force retrofit subscription on different scheduler:

   ```
   new ReactiveLocationProvider(this).getLastKnownLocation()
            .singleOrDefault(null)
            .flatMap(new Func1<Location, Observable<List<OfferLocation>>>() {
                @Override
                public Observable<List<OfferLocation>> call(Location location) {
                        return ARetrofitAPI.getOfferLocations(offer.getId(), latLng).subscribe(Schedulers.io()); //see here
                }
            })
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe();
   ```

- switch observable to different thread just after getting location according to docs: http://reactivex.io/documentation/scheduler.html
   ```
   new ReactiveLocationProvider(this).getLastKnownLocation()
            .singleOrDefault(null)
            .observeOn(Schedulers.io()) //see here
            .flatMap(new Func1<Location, Observable<List<OfferLocation>>>() {
                @Override
                public Observable<List<OfferLocation>> call(Location location) {
                        return ARetrofitAPI.getOfferLocations(offer.getId(), latLng);
                }
            })
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe();
   ```


All three options should work but the first one is most generic and you have to configure it once.

Also I discourage from doing ```.singleOrDefault(null)``` because you have potential NPE.

I hope it helps.

**Comment by KennyGoers** [comment]
Why would the observable returned from the flatMap NOT be associated with the subscribeOn specified in the original code snippet?

**Comment by mcharmas** [comment]
@KennyGoers please check out linked docs how does ```.subscribeOn()``` works.

**Comment by KennyGoers** [comment]
So, what you are saying is that the flatMap() is called from the observeOn() scheduler for this case? I am convinced this isn't problem in the library code base, but a sample as part of the library of this type would help clarify.

And yes I've read those documents many times, but haven't found this addressed specifically. I certainly am in learning phases here.

**Comment by mcharmas** [comment]
@KennyGoers I was surprised by this behavior too but after a while it makes complete sense. OnSubscribe let's you pass the scheduler on which only first initial subscription is handled. In this case, what happens during this time is GMS initialization and registering callback for location updates.

From what I've noticed GMS runs all callbacks in main thread so control is back on main thread. That's where the function you passed to flatMap is called. Default behavior of Retrofit is that it runs on the same scheduler it is called so it is main thread. To switch thread's you can configure it, subscribeOn or just before flatmaping changing scheduler what observeOn does.

The most awesome thing about this is that you can change schedulers multiple times in your observable declaration.

Take a look at the docs, to onSubscribe the blue scheduler is passed and it is used only on initial observable. There is no point in using this method multiple times during observable declaration.

I hope it makes some sense for you. Try creating breakpoints in functions and check the thread on which they are called - this is how I got it.
