### ISSUE TITLE
Observables switch to the Main thread

### ISSUE THREAD

**Issue by Nec1ord** [mcharmas/Android-ReactiveLocation#136]
Here's an observable:

```java
Observable.just(null)
  .observeOn(Schedulers.io())
  .doOnNext(any -> Timber.i("Location settings before - current thread: %s", Thread.currentThread()))
  .flatMap(any -> mRxLocation.checkLocationSettings(settingsRequest))
  .doOnNext(any -> Timber.i("Location settings after - current thread: %s", Thread.currentThread()))
```
And the stack trace:
```java
I/RxLocationPresenter: Location settings before - current thread: Thread[RxIoScheduler-2,5,main]
I/RxLocationPresenter: Location settings after - current thread: Thread[main,5,main]
```

The same issue happens with `getLastKnownLocation` and `getUpdatedLocation`.
Didn't check other observables.

**Comment by mcharmas** [comment]
Yes, this is under the hood behavior of GMS. The callbacks are always called on Main Thread. Check docs of observe on, it should be called after other operator to switch schedulers.

**Comment by Nec1ord** [comment]
It's not obvious that these observables change the operation thread. Please update docs to notify about that.
