### ISSUE TITLE
Places Autocomplete is not working with only Internet enabled

### ISSUE THREAD

**Issue by niyasmohaideen** [mcharmas/Android-ReactiveLocation#138]
Hi,

Thanks for your good library. 

I am facing issue with Places Autocomplete and unable to get fetch the results with Internet connectivity and GPS disabled. It works perfectly when GPS is enabled.  I tried with sample project it behaves in same way. 

Is there any settings property to be set to make it work? Please suggest correct solution to overcome this issue.

**Comment by mcharmas** [comment]
To be honest I have no idea. I am afraid you have to dive into android doc's and check out how it works. I think it has nothing to do with this library since it is just a wrapper around GMS.
