### ISSUE TITLE
where can i put GMS_API_KEY,i can't find it.

### ISSUE THREAD

**Issue by jeffreyxuworld** [mcharmas/Android-ReactiveLocation#143]
Error:(4, 0) Could not get unknown property 'REACTIVE_LOCATION_GMS_API_KEY' for project ':sample' of type org.gradle.api.Project.

I put string name="API_KEY"  in my string.xml,but it also doesn't work.

**Comment by mcharmas** [comment]
Put in in ```~/.gradle/gradle.properties```. I have no idea where this file lives on windows. You can also try putting the key to project local ```gradle.properties``` file.
