### ISSUE TITLE
subscription.unsubscribe(); is not stopping the locationProvider from getting updated location.

### ISSUE THREAD

**Issue by HammadNasir** [mcharmas/Android-ReactiveLocation#146]
I am using `locationProvider.getUpdatedLocation(request)` method in my app like this:

```
locationRequest = LocationRequest.create() //standard GMS LocationRequest
                                                            .setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY)
                                                            .setNumUpdates(1000)
                                                            .setInterval(1000);

                                                    ReactiveLocationProvider locationProvider = new ReactiveLocationProvider(getBaseContext());
                                                    subscription = locationProvider.getUpdatedLocation(locationRequest)
                                                            .subscribe(new Action1<Location>() {
                                                                @Override
                                                                public void call(Location location) {
                                                                    currentLtAU = location.getLatitude();
                                                                    currentLnAU = location.getLongitude();
                                                                    
                                                                    Log.d("cLAT", String.valueOf(currentLtAU));
                                                                }
                                                            });
```
and then trying to unsubscribe this location updates in `onDestroy()` as well as `onStop()` method like this:  `subscription.unsubscribe();`, but even after the activity gets destroyed and stopped, I'm still getting this log:` D/cLAT: 12.1297697` printed out constantly which is not stopping before getting printed out `1000` times.

Please let me know what's causing this and how can I fix it?

**Comment by mcharmas** [comment]
Please provide zip with minimal sample app that reproduces this problem.

**Comment by HammadNasir** [comment]
actually there is no such code I can provide... this is the only code and then `subscription.unsubscribe();` in `onStop()`. What else should I provide?

**Comment by mcharmas** [comment]
Full project that reproduces this isolated problem. You can check out in sample project - there it works as intended. Without such sample I am afraid I am not able to help.

**Comment by HammadNasir** [comment]
@mcharmas Can I give just the code of the activity in which I'm using it?

**Comment by HammadNasir** [comment]
@mcharmas please let me know..

**Comment by HammadNasir** [comment]
@mcharmas but is there any other way of unsubscribing than `subscription.unsubscribe();`? What else could go wrong?  I mean what else conditions can arise this issue?

**Comment by mcharmas** [comment]
I have no idea, it should work. That's why I need project that reproduces it to debug reason.

**Comment by HammadNasir** [comment]
@mcharmas  but my project is quite big, dude. there are many java files... :(

**Comment by mcharmas** [comment]
That's why try replicating this problem in smaller scale.

**Comment by krystianpe** [comment]
I'm facing the same issue. Whenever activity gets recreated it leaks locationUpdates (according to LeakCanary). Here is gist from simple activity that reproduces this issue.  [gist](https://gist.github.com/anonymous/c0a8273d4b327e5a536a1f364e7071d9)

Btw. I'm using rxjava2 and your 0.11 version.

**Comment by mcharmas** [comment]
@krystianpe could you attach report from LeakCanary or attach screenshot?

**Comment by krystianpe** [comment]
here's the [screenshot](http://imgur.com/a/qsy1a)

**Comment by kakashysen** [comment]
Anyone know if this problemas was solved ? o how I can stop update location to reduce the battery consume.
