### ISSUE TITLE
Getting Invalid Response From The server for getting reverse geocoding for Indonesia

### ISSUE THREAD

**Issue by shpleef** [mcharmas/Android-ReactiveLocation#153]
![screen shot 2017-04-04 at 14 33 00](https://cloud.githubusercontent.com/assets/16339855/24656673/a5e0cff0-1943-11e7-86bc-16226608a987.png)

Lat: -6.2087634
Long: 106.845599

**Comment by mcharmas** [comment]
Geocoder sometimes doesn't work on emulators and IOException can be thrown in case of network issues. To handle such exception implement ```onError``` callback (second parameter of ```subscribe``` method).
