### ISSUE TITLE
onConnectionSuspended should not terminate the stream

### ISSUE THREAD

**Issue by edenman** [mcharmas/Android-ReactiveLocation#154]
https://developers.google.com/android/reference/com/google/android/gms/common/api/GoogleApiClient.ConnectionCallbacks.html#onConnectionSuspended(int) says:

`
Called when the client is temporarily in a disconnected state. This can happen if there is a problem with the remote service (e.g. a crash or resource problem causes it to be killed by the system). When called, all requests have been canceled and no outstanding listeners will be executed. GoogleApiClient will automatically attempt to restore the connection. Applications should disable UI components that require the service, and wait for a call to onConnected(Bundle) to re-enable them.
`

Currently, ReactiveLocation does this:
```
        @Override
        public void onConnectionSuspended(int cause) {
            observer.onError(new GoogleAPIConnectionSuspendedException(cause));
        }
```
but this terminates the stream and means that if `onConnected` is later called, it'll get dropped and the Observable won't get any of the resulting events.  

I'd like to propose that this library change to just logging in `onConnectionSuspended`.  If there were a way to propagate this up to the Observable in question, that might be better, but I don't see any easy way to do that with a `Observable<Location>`, for example.  

Let me know if logging is an acceptable solution and I'll put up a PR.

**Comment by mcharmas** [comment]
Hi,
thanks for the proposal. I see the point but I can't see safe and elegant way of handling such behaviour right now. Maybe reconnection on suspend can be achieved with retry operator?

```java
locationProvider
        .getLastKnownLocation()
        .retry(new Func2<Integer, Throwable, Boolean>() {
            @Override
            public Boolean call(Integer integer, Throwable throwable) {
                return throwable instanceof GoogleAPIConnectionSuspendedException;
            }
        })
```

What do you think?

**Comment by edenman** [comment]
Ooh, I like that.  Would you accept something that baked this into the library?

**Comment by mcharmas** [comment]
I am not sure if it should be incorporated into the library.

Do you have any idea how to test such behaviour? How to force GMS to suspend connection?

**Comment by edenman** [comment]
Apparently, you can force it by killing Play Services: https://stackoverflow.com/questions/27350286/onconnectionsuspended-how-to-test-when-will-this-code-be-run

**Comment by mcharmas** [comment]
I had a moment and implemented this feature. If you are interested please test it out.

You can enable this option by passing proper configuration instance to ReactiveLocationProvider constructor.

Changes are can be found here: #165

**Comment by mcharmas** [comment]
Merged. Propagating to maven central. Should be available in few hours.
