### ISSUE TITLE
Use GPS in background service

### ISSUE THREAD

**Issue by nikitoSha** [mcharmas/Android-ReactiveLocation#158]
Hello. I have a service, where I get location updates. All works fine, but... If I will close app (hide, back button), service steel works and app give me not GPS location. I don't see icon about GPS connection in status bar. 

My code is:

>     @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        request = LocationRequest.create() 
                .setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY)
                .setInterval(ThisApp.globals_.updateCurrentLocationDelay);

        locationProvider = new ReactiveLocationProvider(ThisApp.getAppContext());
        if (ActivityCompat.checkSelfPermission(
                this, android.Manifest.permission.ACCESS_FINE_LOCATION) !=
                PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(
                this, android.Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            stopSelf();
        }
        //Подписка на обновление координат
        subscription = locationProvider.getUpdatedLocation(request)
                .subscribe(new Action1<Location>() {
                    @Override
                    public void call(Location location) {
                        if (ThisApp.getGlobals().userIsLogged) {
                            saveCurrentUserLocation(
                                    Double.toString(location.getLatitude()),
                                    Double.toString(location.getLongitude()),
                                    ThisApp.getAppContext());
                        }
                    }
                });

        return super.onStartCommand(intent, flags, startId);
    }

As you see, I was set up Priority to PRIORITY_HIGH_ACCURACY, but getting not GPS location.
I need something like this: LocationManager.GPS_PROVIDER
Please, tell me, how to use GPS connection in background service?
Sorry for my Russian English.

**Comment by nikitoSha** [comment]
I was resolve this problem with permissions. Спасибо, что помогли, гамнаеды.

**Comment by mcharmas** [comment]
Great. Consider using ```requestLocationUpdates(LocationRequest locationRequest, PendingIntent intent)```. It may be better for the batter live and performance for your users. Corresponding method from GMS: https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderApi.html#requestLocationUpdates(com.google.android.gms.common.api.GoogleApiClient, com.google.android.gms.location.LocationRequest, android.app.PendingIntent)
