### ISSUE TITLE
Get List<Address> according current location

### ISSUE THREAD

**Issue by nikitoSha** [mcharmas/Android-ReactiveLocation#159]
Hello, when I try to search some street, I getting address list - all fine, but how can I get sorted results according my current LatLng (I can get this location)?
Yes, I can set max results to 50 and sort Addresses by distance from me to them, but it's not a good idea.
Please, help me.
Sorry for my russian english (mistakes).

**Comment by mcharmas** [comment]
Sorry but this is not an issue of this library but more stackoverflow question.
