### ISSUE TITLE
How many Geofences can be used with this library?

### ISSUE THREAD

**Issue by mori-honest** [mcharmas/Android-ReactiveLocation#160]
In a case application, I need to add about **2000** locations as geofences and keep tracking the entrance and exit from that location.
I've looked at google's android geofence documentation and it says that the maximum number of geofences which can be added to track is **100**.

 So, the question is that do you support **more items** and how **battery friendly** is your algorithm?

**Comment by cyrixmorten** [comment]
This library is a wrapper around the existing API's 

For the geofence API the limit is still 100.

What I have done in my application is that I only actively monitor geofences in a radius of ~1 mile with respect to the device.
Once the device reaches the border of the 1 mile monitoring, I refresh which locations are monitored.

With that approach I managed to avoid hitting the limit of monitored geofences.

**Comment by mcharmas** [comment]
@cyrixmorten thx for replay. You are totally right.
