### ISSUE TITLE
call method not called in some devices

### ISSUE THREAD

**Issue by Sourabhjain90** [mcharmas/Android-ReactiveLocation#163]
In some devices call method not called

locationProvider.getUpdatedLocation(request)
                        .subscribe(new Action1<Location>() {
                            @Override
                            public void call(Location location) {
                                LogManager.d("Location from rx", "" + location);
                                ToastManager.showToast(mContext,"Fetch successfully",true);
                                AppConstants.currentLocation = location;
                                if (mListener != null) {
                                    mListener.onLocationDetected(location);
                                }
                                dismissProgressDialog();
                            }
                        }, new Action1<Throwable>() {
                            @Override
                            public void call(Throwable throwable) {
                                ToastManager.showToast(mContext,"error "+throwable.getMessage(),true);
                                dismissProgressDialog();
                            }
                        });

**Comment by Sourabhjain90** [comment]
Waiting for reply..

**Comment by mcharmas** [comment]
Is there any error? Maybe location is not available and no callback is called?

Please format attached code next time.

**Comment by mcharmas** [comment]
@Sourabhjain90 closing this issue right now. Please reopen with more context.
