### ISSUE TITLE
GoogleAPIConnectionException

### ISSUE THREAD

**Issue by Lir10** [mcharmas/Android-ReactiveLocation#176]
**Device**: Galaxy S7
**Android version** = 7.0

```

pl.charmas.android.reactivelocation2.observables.BaseObservableOnSubscribe$ApiClientConnectionCallbacks.onConnectionFailed (BaseObservableOnSubscribe.java:110)
com.google.android.gms.common.internal.zzad.zzk (Unknown Source)
com.google.android.gms.common.api.internal.zzbd.zzc (Unknown Source)
com.google.android.gms.common.api.internal.zzar.zze (Unknown Source)
com.google.android.gms.common.api.internal.zzar.zza (Unknown Source)
com.google.android.gms.common.api.internal.zzav.zzagz (Unknown Source)
com.google.android.gms.common.api.internal.zzbm.zzc (Unknown Source)
com.google.android.gms.common.api.internal.zzbn.handleMessage (Unknown Source)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6692)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1468)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1358)
```

**Comment by Lir10** [comment]
More from the same device:


**```
Fatal Exception: io.reactivex.exceptions.UndeliverableException
pl.charmas.android.reactivelocation2.observables.GoogleAPIConnectionSuspendedException
io.reactivex.plugins.RxJavaPlugins.onError (RxJavaPlugins.java:349)
io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError (ObservableCreate.java:74)
pl.charmas.android.reactivelocation2.observables.BaseObservableOnSubscribe$ApiClientConnectionCallbacks.onConnectionSuspended (BaseObservableOnSubscribe.java:105)
com.google.android.gms.common.internal.zzad.zzce (Unknown Source)
com.google.android.gms.common.api.internal.zzbd.zzf (Unknown Source)
com.google.android.gms.common.api.internal.zzao.onConnectionSuspended (Unknown Source)
com.google.android.gms.common.api.internal.zzbl.onConnectionSuspended (Unknown Source)
com.google.android.gms.common.api.internal.zzw.onConnectionSuspended (Unknown Source)
com.google.android.gms.common.internal.zzab.onConnectionSuspended (Unknown Source)
com.google.android.gms.common.internal.zzh.handleMessage (Unknown Source)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6692)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1468)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1358)
```**

**Comment by Lir10** [comment]
Check the solution on #175

**Comment by mcharmas** [comment]
@Lir10 Should be fixed in 2.1. Propagating to maven central. Should be available in few hours.

**Comment by renegens** [comment]
Hello, I am not seeing the RxJava 1 fix for this on maven. Can you point me to it?

**Comment by Jeel-Shah** [comment]
@renegens Did you find a workaround for this in the time being?

**Comment by renegens** [comment]
@Jeel-Shah No fix, just catching it and reporting it.
