### ISSUE TITLE
getCurrentPlace(null): PlaceLikelihoodBuffer always return statusCode ERROR

### ISSUE THREAD

**Issue by gukzilla** [mcharmas/Android-ReactiveLocation#187]
return Status{statusCode=ERROR, resolution=null}

> locationProvider.getCurrentPlace(null)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .doOnNext(placeLikelihoods -> hideProgress())
                .map(placeLikelihoods -> {
                    Status status = placeLikelihoods.getStatus();
                    if (status.isSuccess()) {
                        return placeLikelihoods;
                    } else {
                        placeLikelihoods.release();
                        throw new IllegalStateException("Status ERROR: " + status.getStatusMessage());
                    }
                })
                .map(this::convertPlaces)
                .subscribe(places -> mLocationAdapter.setMyPlaces(places),
                        throwable -> Logger.e(throwable, TAG));

getPlaceAutocompletePredictions(searchQuery, null, filter) works properly
What can be wrong?

**Comment by mcharmas** [comment]
No idea. As you can see in sources ```LocationProvider.getCurrentPlace``` wraps around ```getCurrentPlace``` GMS method call, not ```getPlaceAutocompletePredictions```. You can see in the sources that it is just a wrapper.

**Comment by gukzilla** [comment]
@mcharmas I understand that the problem is in the play services. But maybe you came across this?

**Comment by mcharmas** [comment]
Sorry, I didn't...

**Comment by yalematta** [comment]
I've got the same problem! Any solutions found?
