### ISSUE TITLE
setinterval(8*1000) not triggering the update on 8 sec but it is triggering each second!

### ISSUE THREAD

**Issue by kailash09dabhi** [mcharmas/Android-ReactiveLocation#24]
locationProvider.getUpdatedLocation(
                LocationRequest.create()
                        .setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY)
                        .setNumUpdates(1500)
                        .setInterval(8*1000);
This code i used but it seems like interval not working with seconds value.

but if i use this  .setInterval(6*6*1000) value then it gives me request each 7 seconds.
So may be i am confused setting interval .Can you please guide.

P.S. Thank man for your smart work..!

**Comment by mcharmas** [comment]
Hi, to me honest I am not sure how this is supposed to work because this part of original GMS API. Please try to reffer to documentation to get proper behaviour - I hope you find sth usefull here:
http://developer.android.com/reference/com/google/android/gms/location/LocationRequest.html

**Comment by kailash09dabhi** [comment]
oh okay thanks man.

**Comment by sytolk** [comment]
You have no setFastestInterval(). Do you read this? setInterval (long millis)
This interval is inexact. You may not receive updates at all (if no location sources are available), or you may receive them slower than requested. You may also receive them faster than requested (if other applications are requesting location at a faster interval). The fastest rate that that you will receive updates can be controlled with setFastestInterval(long). By default this fastest rate is 6x the interval frequency.

**Comment by kailash09dabhi** [comment]
Yes sytolk you right.I was just busy to post the comment.In setting fastest interval this works perfect. You are right, We need to set the fastest interval so we get the updates according to the interval.Thanks :)

**Comment by saxenahysm** [comment]
I have the relevant issue,
val request =  create().setPriority(Priority.PRIORITY_HIGH_ACCURACY).setInterval(interval).setFastestInterval(interval)

code is working exactly what i want but when device is in sleep mode the interval time is random (6sec,10sec, 1minut, or some time more than 1minuts,)

Any guess what is the exact issue with LocationRequest
