### ISSUE TITLE
Location Update Intervals

### ISSUE THREAD

**Issue by sytolk** [mcharmas/Android-ReactiveLocation#25]
It`s have one problem with GMS intervals (setInterval() and setFastestInterval()).
http://developer.android.com/reference/com/google/android/gms/location/LocationRequest.html
How to receive location updates depending of the speed? 
If Android device move = faster location update, 
If stay on one place = slower location update.
Maybe this can be done with filter() in Android-ReactiveLocation ?

**Comment by sytolk** [comment]
Its need filter for ActivityRecognition result.

**Comment by sytolk** [comment]
I have try ActivityRecognition in Application instead Activity and its not work :)
I have not see any detected activities Log.i("DetectedActivity", "detectedActivity=" + detectedActivity.toString());
Maybe broadcast receiver not receive activity recognition. Location updates works from Application. I will try this in service.. its need background activity recognition.

```java
public class MyApplication extends Application {

private ReactiveLocationProvider locationProvider;
private Observable<ActivityRecognitionResult> activityObservable;

public void onCreate() {
        super.onCreate();

        locationProvider = new ReactiveLocationProvider(getApplicationContext());
        activityObservable = locationProvider.getDetectedActivity(50);
        subscriptionAR = activityObservable.map(new ToMostProbableActivity())
                .subscribe(new Action1<DetectedActivity>() {
                    @Override
                    public void call(DetectedActivity detectedActivity) {
                        Log.i("DetectedActivity", "detectedActivity=" + detectedActivity.toString());
                    }
                }, new ErrorHandler());
    }
}
```

**Comment by mynavy** [comment]
detectedActivity.toString() will return null and thats why you cant see the result.

You should convert the type to string. 

Use this Function: 

private String getNameFromType(int activityType) {
        switch (activityType) {
            case DetectedActivity.IN_VEHICLE:
                return "in_vehicle";
            case DetectedActivity.ON_BICYCLE:
                return "on_bicycle";
            case DetectedActivity.ON_FOOT:
                return "on_foot";
            case DetectedActivity.STILL:
                return "still";
            case DetectedActivity.UNKNOWN:
                return "unknown";
            case DetectedActivity.TILTING:
                return "tilting";
        }
        return "unknown";
    }

And Call to this function like this : getNameFromType(detectedActivity.getType())

**Comment by sytolk** [comment]
ActivityRecognition is too slow for this. Its better to get speed from Location Object and filter sending coordinates on server based on speed.

**Comment by mynavy** [comment]
yeah you are right but how do u get speed constantly? it will drain the battery

**Comment by mynavy** [comment]
For example if you are trying to detect when the user walking outside his house then you should fetch his speed every minute forever which will drain battery . 

I think would be better to read the result from the sensors and decide if the user is walking for example which will be faster i guess.

**Comment by sytolk** [comment]
Yes but it depend of the Application. I have use this for local taxi application used in cars with power charger plugged in tablet. I can get location updates every second. To minimize internet traffic is more important than device battery :)
With ActivityRecognition walking will be changed on some devices after 20-30 seconds

**Comment by mynavy** [comment]
as far as i know Activity Recognition is using accelerometer  + location to detect your current activity. 

I guess it takes some time to recognize your current activity because it's not checking your location every minute to reduce battery consumption.
