### ISSUE TITLE
GeoFencing not working

### ISSUE THREAD

**Issue by kailash09dabhi** [mcharmas/Android-ReactiveLocation#26]
I tried to use the geofencing but it is not triggering any event on enter and exit. But with the same code pending intent and geofencing request i used the default google play library then working. So i think geofencing has some problem. Can you please guide?

**Comment by mcharmas** [comment]
Hmm.. I'll try take a look at it tomorrow. In the meantime could you check how your implementation of library is different from what we are doing in observables from the library? Maybe you can spot what is wrong. There is not much code using this APIs so it should be fairly easy to spot.

**Comment by mcharmas** [comment]
@kailash09dabhi do you still have problems with geofencing? I've just written submited a push with geofencing sample - seems to work well. Try it out and let me know.
