### ISSUE TITLE
Support for Google Play Services 7.0 APIs

### ISSUE THREAD

**Issue by kboyarshinov** [mcharmas/Android-ReactiveLocation#32]
Google Play Services 7.0 has new location related APIs:
- Places API
- LocationSettings API

More info: http://android-developers.blogspot.ru/2015/03/google-play-services-70-places-everyone.html

**Comment by mcharmas** [comment]
@kboyarshinov I've added support for places api and location settings. Check out how it works - it's in [places-api](https://github.com/mcharmas/Android-ReactiveLocation/tree/places-api) branch. The lib is also released as 0.5-SNAPSHOT version.

I would be grateful if you could check it out. Do you have any ideas about other APIs from GMS7.0 that can be added to this library considering Places API and LocationSettings API?

BTW Your pull request is included in this branch so it will be merged to new version later this week.

**Comment by kboyarshinov** [comment]
@mcharmas Great! I'll check this out.

**Comment by kboyarshinov** [comment]
@mcharmas Looks good to me. Except `TextObservable` in sample. It does the same thing as RxAndroid's `WidgetObservable.text()`.

**Comment by mcharmas** [comment]
Awesome! I had no idea that text observable is there - missed it somehow. I'll fix that and release new version later today. Thanks for taking a look at it.

**Comment by mcharmas** [comment]
I've just released new version. Should be in maven centra in few hours. Thx for help.

**Comment by kboyarshinov** [comment]
:+1: Thanks
