### ISSUE TITLE
rx.android... import problem.

### ISSUE THREAD

**Issue by milosjovac** [mcharmas/Android-ReactiveLocation#34]
I'm exploring your library and Sample project cannot be built. 

Import rx.android.whatever in utils/TextObservable.java is invalid. rx.Observable and rx.functions.Func1 are OK, but every import with 'android' in name is with error. I checked RxJava repo and android package is not in the source code O_o. 

Is your sample project runnable?

**Comment by mcharmas** [comment]
Yes, the project should be runnable. rx.android comes from dependency called io.reactivex:rxandroid. I have no idea what is the case. Maybe try reimporting project.

**Comment by rishibaldawa** [comment]
I had the same issue. Think the readme is missing the RxAndroid import

```
    compile 'pl.charmas.android:android-reactive-location:0.5@aar'
    compile 'com.google.android.gms:play-services-location:7.0.0'
    compile 'io.reactivex:rxjava:1.0.8'
    compile 'io.reactivex:rxandroid:0.24.0'
```

**Comment by mcharmas** [comment]
The thing is that you don't have to use rxandroid to use this library. You have some alternatives to that like https://github.com/JakeWharton/NotRxAndroid. Only RxJava is required for the library to work. Please notice that sample project has rxandroid as dependency and should compile. I'll add and info to README in sake of clarification.

**Comment by mcharmas** [comment]
Added info to README. Closing.
