### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by kgritesh** [mcharmas/Android-ReactiveLocation#35]
I want to use [Sourcegraph](https://sourcegraph.com) for Android-ReactiveLocation code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/mcharmas/Android-ReactiveLocation. (It should only take 30 seconds.)

Thank you!

**Comment by mcharmas** [comment]
Done.
