### ISSUE TITLE
Can not get getLastKnownLocation to run as blocking call

### ISSUE THREAD

**Issue by jfey** [mcharmas/Android-ReactiveLocation#42]
Hello,

I am hitting the wall since quite a while. No I try to get a solution here. My problem:

When i use the basic call as shown in the Readme

ReactiveLocationProvider locationProvider = new ReactiveLocationProvider(context);
locationProvider.getLastKnownLocation()
    .subscribe(new Action1<Location>() {
        @Override
        public void call(Location location) {
            doSthImportantWithObtainedLocation(location);
        }
    });

the call comes back as expected asynchronously at a later stage. Thats fine. In some areas i really need to wait till the result is already back before proceeding. I tried solutions like:

```
        locationProvider.getLastKnownLocation()
                .subscribeOn(Schedulers.newThread())  
                .observeOn(Schedulers.newThread())
                .toBlocking()

                .forEach(new Action1<Location>() {
                   @Override
                   public void call(Location location) {
                       setLocation(location);
                       Timber.i(CommonValues.TAG, "jo!");
                   }
               });
```

This one never comes back - i am getting a threading exception "down under". 

The really strange thing is that at yet another area in the code i am using this:

```
    Observable<Location> locationObservable = LastKnownLocationObservable.createObservable(ctx);
    Iterable<Location> locations = BlockingObservable.from(locationObservable).toIterable();
    Location location = locations.iterator().next();
```

and it works! (But not in other areas of the code).

Has someone any hint what is wrong here?

Besides that i really like the library and maaaany thanks for it and also the frequent updates.

cheers

Juergen

**Comment by mcharmas** [comment]
Hmm, I guess we have a deadlock here.
I think the reason for such behaviour is that GMS callbacs may be executed in main thread that is locked waiting for result.

I wonder why the other example is working. Are you making these calls from another thread?
I've tried to reproduce it and I am getting the same locked behaviour.

To be honest I have no idea how to solve this. I think it's not possible to implement this blocking from main thread.

**Comment by jfey** [comment]
Ok, thanks for you trying to dig the problem. I'd fear a thread deadlock scenario but hoped or a "miracle". I am now trying to re-arrange my code - maybe moving it to a single class, which runs in the main thread. If i get it running i will respond here.

**Comment by athornz** [comment]
I've also run into this issue. Did you ever find a solution?

**Comment by mcharmas** [comment]
Nothing new in this subject. I am almost confident that it's impossible to do that due to mechanics of GMS.

**Comment by mandybess** [comment]
I think I found the issue here... `GoogleApiClient.Builder` has a `setHandler` method. According to the documentation: 
```
Sets a Handler to indicate which thread to use when invoking callbacks. Will not be used directly to handle callbacks. If this is not called then the application's main thread will be used.
```

Since this library doesn't call `setHandler` the main thread is being used to handle callbacks.

**Comment by mcharmas** [comment]
@mandybess great discovery. I still have to figure out how to use this in the library without breaking behaviour in all the apps that are using it.

Definitelly will take a look at it when releasing new version.
