### ISSUE TITLE
Location updates not working when WiFi is enabled.

### ISSUE THREAD

**Issue by 2bard** [mcharmas/Android-ReactiveLocation#43]
Apologies if i'm doing something wrong here.

I'm subscribing for location updates but I only get the updates when wifi is turned off

My code:

    LocationRequest request = LocationRequest.create() //standard GMS LocationRequest
            .setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY)
            .setSmallestDisplacement(0.1f)
            .setNumUpdates(5)
            .setInterval(100);

    Subscription subscription = locationProvider.getUpdatedLocation(request)
            .subscribe(new Action1<Location>() {
                @Override
                public void call(Location location) {
                  //do stuff
                }
            });

As soon as I disable wifi I start receiving the updates.

**Comment by mcharmas** [comment]
Sorry but I have no idea what can be wrong here. Maybe try using bare GMS and check if the result is the same. I doubt it the library issue but you never know. Can you investigate it futher?

**Comment by sytolk** [comment]
The problem can be in setSmallestDisplacement(0.1f) - and user not move.
https://developer.android.com/reference/com/google/android/gms/location/LocationRequest.html#setSmallestDisplacement%28float%29
 Try to remove setSmallestDisplacement setNumUpdates and check again.

**Comment by 2bard** [comment]
False alarm, the strange behaviour was a result of third party privacy software installed on the test device. Sorry for wasting your time!
