### ISSUE TITLE
Extending library to support others Google Play APIs?

### ISSUE THREAD

**Issue by kamiox** [mcharmas/Android-ReactiveLocation#44]
What do you think about extracting from library the base module with the GoogleAPIClientObservable and all related class? So we could build upon one base all API specific modules. 

BTW Thanks to all contributors, good work, keep going :)

**Comment by mcharmas** [comment]
@kamiox it may be good idea. Probably it would be good idea for it to be in separate repository for modules to be independent. What do you think about it? What modules and features do you have in mind?

**Comment by passsy** [comment]
I would prefer the same split as the Google Play services. So we are able to select the minimum pieces and the matching Rx wrappers.

**Comment by Rainer-Lang** [comment]
@passsy +1

**Comment by richarddd** [comment]
@passsy +1. I would to see this library work for other play services and splitting it up!

**Comment by kiwiandroiddev** [comment]
@passsy +1. I'd be very interested in Rx wrappers for the Google Fit APIs

**Comment by alorma** [comment]
New AwernessAPI looks so cool

**Comment by mcharmas** [comment]
This library is location focused and I don't intend to wrap other APIs.
