### ISSUE TITLE
does it make sense to support all Places like APIs?

### ISSUE THREAD

**Issue by kaushikgopal** [mcharmas/Android-ReactiveLocation#51]
for example if i wanted to search for a place (hotel) at a particular location? i get a sense that most of the current features revolve around the user's current location. if that is the intent, then supporting such a feature doesn't make sense.

was just curious if this would be a feature you're willing to consider (say if a PR was sent your way)

**Comment by mcharmas** [comment]
Of course I am willing to consider such feature. Some of the Places APIs are implemented. What particular do you have in mind? Maybe before implementing let's first discuss the ideas here.

The idea of this library is to reduce boilerplate from location releated Google Play Services so I guess it would fit:-)

**Comment by kaushikgopal** [comment]
>  What particular do you have in mind?

I was thinking  about the use case i mentioned in the description i.e. if i wanted to search for a specific place (for e.g. like a hotel) at a particular location? For e.g. search for a "Holiday Inn" hotel in "San Francisco, USA".

*i get a sense that most of the current features revolve around the user's **current** location*. does it make sense to add apis, that allow users to search for a different location? (i.e. not current location).

if that doesn't make sense, i can maybe try to explain with a detailed api.

**Comment by mcharmas** [comment]
Did you take a look at this: https://github.com/mcharmas/Android-ReactiveLocation#places-api

This is part of places API implemented in this library. What APIs from GMS would you like to add?
