### ISSUE TITLE
Dex method count

### ISSUE THREAD

**Issue by IgorGanapolsky** [mcharmas/Android-ReactiveLocation#56]
Hello,
I just ran a dexcount gradle plugin on your repo, and your sample-debug.apk has <b>25782</b> methods.  That is 40% of the allowed limit in dex on Android!  Is there any way to exclude dependencies?  I am using your library in my project, and I am afraid it's decimating my dexcount as well.

Thanks,
Igor

**Comment by pranaysharma** [comment]
wow thats a lot :|. Interested in the reply.

**Comment by mcharmas** [comment]
Hmm, it's interesting. I've hit the limit using this library but that was caused by guava and google play services which are huge. Take a look at whole dependency tree for sample project:

```
+--- com.android.support:appcompat-v7:22.1.1
|    \--- com.android.support:support-v4:22.1.1
|         \--- com.android.support:support-annotations:22.1.1
+--- io.reactivex:rxandroid:0.24.0
|    \--- io.reactivex:rxjava:1.0.4 -> 1.0.10
\--- project :android-reactive-location
     +--- com.google.android.gms:play-services-location:7.3.0
     |    +--- com.google.android.gms:play-services-base:7.3.0
     |    |    \--- com.android.support:support-v4:22.0.0 -> 22.1.1 (*)
     |    \--- com.google.android.gms:play-services-maps:7.3.0
     |         \--- com.google.android.gms:play-services-base:7.3.0 (*)
     \--- io.reactivex:rxjava:1.0.10
```

There is nothing here actually. Of course except of huge play services and rxjava.
Maybe RxJava is so big? What tool are you using to measure it?

**Comment by IgorGanapolsky** [comment]
I am using https://github.com/KeepSafe/dexcount-gradle-plugin

**Comment by mcharmas** [comment]
@IgorGanapolsky I've checked method count and here are results:

```
// librart + required dependencies
330      pl.charmas.android.reactivelocation
3855    rx
6812    com.google.android.gms - location play services
// total ~10K

// not required dependencies of sample project
11530    android.support
```

So library with dependencies including GMS is around 10K methods and I can't imagin that anything could be done about it.

Sample project is larger due to usage of android support libraries that add another 12K.
