### ISSUE TITLE
Feature Request: unit tests

### ISSUE THREAD

**Issue by IgorGanapolsky** [mcharmas/Android-ReactiveLocation#61]
Can you please consider adding unit tests to your library or sample?  I would like to see stuff similar to`MockWebServer`, `MockResponse`, and `MockRetrofit`.  This will explain how to test the networking calls which are being made by this library.

**Comment by mcharmas** [comment]
Just mock whole ```ReactiveLocationProvider``` instance and return custom location observables for test purposes.
