### ISSUE TITLE
getLastKnownLocation() doesn't call next() if GPS is off

### ISSUE THREAD

**Issue by LShuttneab** [mcharmas/Android-ReactiveLocation#65]
The getLastKnownLocation() method defaults to calling "observer.onCompleted()", skipping onNext() if the location is null

https://github.com/mcharmas/Android-ReactiveLocation/blob/master/android-reactive-location/src/main/java/pl/charmas/android/reactivelocation/observables/location/LastKnownLocationObservable.java#L29

This makes it difficult to chain with other observables: 

```
 Subscription subscription = locationProvider.getLastKnownLocation()
            .timeout(LOCATION_TIMEOUT_IN_SECONDS,
                     TimeUnit.SECONDS,
                     Observable.just((Location) null))
            .onErrorResumeNext(Observable.just((Location) null))
            .concatWith(locationProvider.getUpdatedLocation(req))
            .distinctUntilChanged()
            .subscribe(this::updateLocationIfPossible);
```

In this example, I would like to get a `null` location so that I can react accordingly, in this case I prompt the user to enable GPS. Then, once GPS is on, the observable will emit the updated location and I can again take action.

**Comment by LShuttneab** [comment]
I'm using this as a work around for now

```
    Subscription subscription = locationProvider.getUpdatedLocation(req)
            .timeout(LOCATION_TIMEOUT_IN_SECONDS,TimeUnit.SECONDS,Observable.just((Location)null))
            .concatWith(locationProvider.getUpdatedLocation(req))
            .distinctUntilChanged()
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(this::updateLocationIfPossible);
```

**Comment by mcharmas** [comment]
Hi,
First version of library implemented this behavoiur the way you expect it work but taking a look at Observable sematics this neded a change. Null location is no location, so it is maps to empty observable.

If you really care about the null value you can use RxJava operators for this. For example:

```
locationProvider
                .getLastKnownLocation()
                .singleOrDefault(null)
                ...
```

Much better option would be to embrace null safety with ```switchIfEmpty``` operator:

```
locationProvider
                .getLastKnownLocation()
                .switchIfEmpty(locationProvider.getUpdatedLocation(req))
                ....
```

I hope that these to options to solve this problem help.

**Comment by LShuttneab** [comment]
Thanks for the reply, 

    I think I jumped the gun when I stated that I wanted a `null` value for location, I was giving you desired implementation details when I should have been stating desired outcome. 

I'm trying to construct an observable that tells me the current location and then gives me updates whenever it changes. If it's unable to get the location I would like to notify the user, then once Location services are turned on, I would like the same subscription to emit the updated location.

Is there a better way I can use your library to achieve my goal? The second option still doesn't look like it solves the problem of being able to notify the user when I am unable to determine location (the first option sounds like one you don't recommend, and I'd like to learn the "most correct" way).

It seems like a `doIfEmpty()` would be my best option, but I don't think one exists.

**Comment by mcharmas** [comment]
Hmm, everything depends what's more readable for you. I hope I understood you well.

First thought how I would to that without null would be sth like this:

```
        locationProvider
                .getLastKnownLocation()
                .switchIfEmpty(Observable.empty().doOnCompleted(() -> notifyUserNoLastKnownLocationAvailable()))
                .concatWith(locationProvider.getUpdatedLocation(req))
```

Using null:

```
        locationProvider
                .getLastKnownLocation()
                .singleOrDefault(null)
                .doOnNext(location -> {
                    if (location == null) {
                        notifyUserNoLastKnownLocationAvailable();
                    }
                })
                .concatWith(locationProvider.getUpdatedLocation(req))
```

Maybe there is event cleaner solution to this problem but both of the above are good enough for me. I honestly prefer coding without nullchecks if I have a chance to do that.

**Comment by LShuttneab** [comment]
That first option seems like a perfect solution. Thanks for taking the time to help me out w/ this (as well as making the library).
