### ISSUE TITLE
How can I get remain app to continue ping with PINGING symobol on status bar ?

### ISSUE THREAD

**Issue by homedevs** [mcharmas/Android-ReactiveLocation#70]
![device-2015-09-02-221944](https://cloud.githubusercontent.com/assets/11264134/9638321/c6f9c7f8-51c3-11e5-9509-6720547a3402.png)

I want to show LEFT side GPS location pinging symbol. How can I show ?

**Comment by farmazon3000** [comment]
you have to show that notification by yourself (e.g. start a foreground service and provide it with an icon)
