### ISSUE TITLE
Get location using GPS satellites if 'Use wireless networks' options is not checked

### ISSUE THREAD

**Issue by alirezaaa** [mcharmas/Android-ReactiveLocation#71]
Hi,

I'm using following codes and everything is okay if the 'Use wireless networks' options is checked but that's not enough good to get location, because if a user turned that option off, this library will not work and it cannot get location using GPS satellites option. How can I force this library to get location using GPS satellites if 'Use wireless networks' option is not checked?

**Comment by mcharmas** [comment]
Hi,
this library is only a reactive wrapper on google play services so probably you have to prepare backup LocationRequest object based on ```checkLocationSettings``` result.

Sorry, but I don't have ready solution for you.

**Comment by alirezaaa** [comment]
@mcharmas Thanks for your answer. You're library is really good but in my case, I need to get location always and I decided to get location only using GPS.
