### ISSUE TITLE
Cannot use play services 8.1.0

### ISSUE THREAD

**Issue by IgorGanapolsky** [mcharmas/Android-ReactiveLocation#73]
Hello,
I keep getting a crash:
> IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread. 
IncompatibleClassChangeError: The method 'void com.google.android.gms.common.api.GoogleApiClient.connect()'

Please advise.

**Comment by dbachelder** [comment]
There is a pull request to fix this: https://github.com/mcharmas/Android-ReactiveLocation/pull/72

We are manually building that fork for our project at the moment.
