### ISSUE TITLE
Geofences get deleted?

### ISSUE THREAD

**Issue by mynavy** [mcharmas/Android-ReactiveLocation#74]
Hello ,

I've noticed lately that when users are updating the app , all geofences are deleted?
is that possible to keep them even when app is updating?

Thanks.

**Comment by IgorGanapolsky** [comment]
@mynavy. Updating how?  This app is not listed on Play Store.

**Comment by mynavy** [comment]
I meant my app *

**Comment by IgorGanapolsky** [comment]
Which users are updating 'your' app?

**Comment by mynavy** [comment]
I've released an app in beta version . 
I have some users who are testing the app , and when ever im updating the version of the app all previous geofences gets deleted.

**Comment by mcharmas** [comment]
@mynavy I am afraid you have to manually register all geofences again after application upgrade the same way as you have to do it after device restart.

Doing it after device restart is pretty easy, you just have to declare broadcast receiver with BOOT_COMPLETED action. There is similar way to listen for app update broadcasts. Description how to do this you can find here: http://stackoverflow.com/questions/2133986/how-to-know-my-android-application-has-been-upgraded-in-order-to-reset-an-alarm

**Comment by mynavy** [comment]
Thanks for the quick answer!
Will try it :+1:
