### ISSUE TITLE
Google Play Services 8.1.0 support?

### ISSUE THREAD

**Issue by renaudcerrato** [mcharmas/Android-ReactiveLocation#75]
Not sure why, but if I update GPS to 8.1.0 I can't get any fix from my ReactiveLocationProvider... No error thrown, no completion. Any clue?

**Comment by IgorGanapolsky** [comment]
Because 8.1.0 hasn't been integrated into the library yet.

**Comment by renaudcerrato** [comment]
Thanks for the prompt reply. Since there was no compile errors, I assumed GPS 8.1.0 was compatible with the previous one. 

Thanks!
