### ISSUE TITLE
Unimplemented exception

### ISSUE THREAD

**Issue by Grzelazny** [mcharmas/Android-ReactiveLocation#76]
Hi, looks like some exception handling method is not implemented. 

Here is my stack:

java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
1	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
2	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
3	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
4	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
5	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
6	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
7	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
8	at java.lang.Thread.run(Thread.java:841)
9Caused by: rx.exceptions.OnErrorNotImplementedException
10	at rx.Observable$27.onError(Observable.java:7535)
11	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
12	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
13	at rx.internal.operators.OperatorSubscribeOn$1$1$1.onError(OperatorSubscribeOn.java:71)
14	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:197)
15	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
16	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
17	... 7 more
18Caused by: rx.exceptions.MissingBackpressureException
19	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:138)
20	at rx.internal.operators.OperatorSubscribeOn$1$1$1.onNext(OperatorSubscribeOn.java:76)
21	at pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable$1.onLocationChanged(LocationUpdatesObservable.java:36)
22	at com.google.android.gms.internal.nj$a.handleMessage(Unknown Source)
23	at android.os.Handler.dispatchMessage(Handler.java:102)
24	at android.os.Looper.loop(Looper.java:146)
25	at android.app.ActivityThread.main(ActivityThread.java:5692)
26	at java.lang.reflect.Method.invokeNative(Native Method)
27	at java.lang.reflect.Method.invoke(Method.java:515)
28	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
29	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
30	at dalvik.system.NativeStart.main(Native Method)

**Comment by phajduk** [comment]
@Grzelazny could you provide more details about context of this exception? I see in stacktrace that the cause of it is `MissingBackpressureException` which means that your subscriber is too slow and it consumes emitted values slower than emitter is emitting. On your side you can use `onBackpressureDrop()` method to just omit such values.
