### ISSUE TITLE
Upgrade to io.reactivex:rxandroid:1.0.1

### ISSUE THREAD

**Issue by farmazon3000** [mcharmas/Android-ReactiveLocation#78]
Upgrade to io.reactivex:rxandroid:1.0.1, now some old io.reactivex:rxandroid:0.25.0 is used.

**Comment by IgorGanapolsky** [comment]
Is this compatible with Play Services 8.1.0?

**Comment by farmazon3000** [comment]
@IgorGanapolsky you're asking if io.reactivex:rxandroid:1.0.1 is compatible with Play Services 8.1.0? Is there any dependency between those two?

**Comment by IgorGanapolsky** [comment]
Of course, they have to match in gradle.

**Comment by farmazon3000** [comment]
Can you direct me where this dependency is defined?

**Comment by IgorGanapolsky** [comment]
In build.gradle

**Comment by mcharmas** [comment]
There is absolutely no dependency. RxAndroid is only used in sample app.

czw., 1.10.2015, 20:17 Filip użytkownik <notifications@github.com> napisał:

**Comment by farmazon3000** [comment]
Ah, now I see there is
```
//RxAndroid or NotRxAndroid is not required by library

```
What is "NotRxAndroid"?

**Comment by farmazon3000** [comment]
Ah, now I see there is
```
//RxAndroid or NotRxAndroid is not required by library

```
Then this issue is pointless and should be closed.

BTW: What is "NotRxAndroid"?

**Comment by mcharmas** [comment]
I guess it was alternative to RxAndroid few months ago. Afterwards
RxAndroid 1.0 and RxBindings emerged. Probably docs need a change.
W dniu czw., 1.10.2015 o 20:23 Filip <notifications@github.com> napisał(a):
