### ISSUE TITLE
Runtime permissions

### ISSUE THREAD

**Issue by jkwiecien** [mcharmas/Android-ReactiveLocation#79]
Does the lib cover Runtime permissions? If not it should be updated according to docs: https://developers.google.com/android/reference/com/google/android/gms/location/SettingsApi

I could work on it but what class should I look into? :)

**Comment by mynavy** [comment]
+1 for Runtime permissions

**Comment by Talgat777** [comment]
+1

**Comment by lukaville** [comment]
+1

**Comment by phajduk** [comment]
@jkwiecien @mynavy @lukaville I think for checking `LocationSettingsStates` you have [this](https://github.com/mcharmas/Android-ReactiveLocation/blob/6344ffe063b69fad3fb55729c6fa83c684d04de0/android-reactive-location/src/main/java/pl/charmas/android/reactivelocation/ReactiveLocationProvider.java#L253-L261) method and for more complex things there's [RxPermissions](https://github.com/tbruyelle/RxPermissions) library. Did I missed something?

**Comment by mcharmas** [comment]
@phajduk thanks for your response. Agree completely but was not aware of RxPersmissions library. Great discovery. 

I think that this library is not intended to support every android API out there. It is mean't to be a wrapper around Google Play location Services.
