### ISSUE TITLE
Hii , App crash whenever click upon places

### ISSUE THREAD

**Issue by cq321** [mcharmas/Android-ReactiveLocation#80]
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:  Caused by: java.lang.IllegalStateException
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at com.google.android.gms.common.internal.zzu.zzU(Unknown Source)
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at com.google.android.gms.common.data.zzc.zzbf(Unknown Source)
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at com.google.android.gms.common.data.zzc.<init>(Unknown Source)
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at com.google.android.gms.location.places.internal.zzt.<init>(Unknown Source)
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at com.google.android.gms.location.places.internal.zzm.<init>(Unknown Source)
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at com.google.android.gms.location.places.PlaceLikelihoodBuffer.get(Unknown Source)
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at pl.charmas.android.reactivelocation.sample.PlacesActivity$2.call(PlacesActivity.java:70)
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at pl.charmas.android.reactivelocation.sample.PlacesActivity$2.call(PlacesActivity.java:67)
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at rx.Observable$30.onNext(Observable.java:7545)
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at rx.android.app.OperatorConditionalBinding$1.onNext(OperatorConditionalBinding.java:79) 
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:208) 
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170) 
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:808) 
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:103) 
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193) 
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5341) 
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830) 
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:646) 
10-14 19:33:34.308 30942-30942/pl.charmas.android.reactivelocation.sample E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by pranaysharma** [comment]
Hi Any leads on this?

**Comment by mcharmas** [comment]
Have you properly configured the sample application according to https://github.com/mcharmas/Android-ReactiveLocation#sample?

**Comment by pranaysharma** [comment]
Thanks a lot :) Was unable to figure out problem

**Comment by cq321** [comment]
Thanks mcharmas
