### ISSUE TITLE
Service for background location update

### ISSUE THREAD

**Issue by sytolk** [mcharmas/Android-ReactiveLocation#81]
This service is missing in samples:
https://github.com/mcharmas/Android-ReactiveLocation/issues/29#issuecomment-75074628
I think that its need sample for this to avoid common mistakes and will make PR.

**Comment by farmazon3000** [comment]
Can you be more specific what you need?

**Comment by sytolk** [comment]
Background location update for example to send location every 4 seconds on Rest service after user close the app and Android kill it :)

**Comment by mcharmas** [comment]
Due to changes in Android Oreo background service with location updates will not work. The way to go is to use ```ReactiveLocationProvider#requestLocationUpdates``` with PendingIntent to BroadcastReceiver. See https://developer.android.com/about/versions/oreo/background.html.

**Comment by sytolk** [comment]
or better use with: https://github.com/firebase/firebase-jobdispatcher-android
