### ISSUE TITLE
One Shot Location

### ISSUE THREAD

**Issue by sdoward** [mcharmas/Android-ReactiveLocation#82]
I have a requirement to obtain 1 location update and then close the stream. Potentially this could be done with a timeout as well.

Do you see this as being part of the library? If so I am happy to contribute.

**Comment by sytolk** [comment]
Yes I think its needs to have more samples for this library. Please make a PR.

**Comment by sdoward** [comment]
I believe it can have a place in the lib itself. It would be the Android-ReactiveLocation equivalent of `Observable.just` but of course to get a location we need to wait for an undetermined amount of time, which means we are unable to use `Observable.just`

Further more it's a common use case to obtain 1 location rather than a stream and this feature would mean that there is no need unsubscribe in the onNext(). 

That would mean that the lib would contain

- `LocationUpdatesObservable`
- `LastKnownLocationObservable`
- `OneShotLocationObservable`

A more concrete example (which applies to me) is that one might need to obtain a location in the middle of a stream by using `.zip`. And thus not keep the location detection on whilst the original stream is hot.

Is this a valid reason for inclusion in the lib?

**Comment by mcharmas** [comment]
Maybe I don't understand something in this discussion but it his behavior can be achieved by standard .single() or .first() RxJava operator.

**Comment by sdoward** [comment]
No you didn't misunderstand. I just wasn't aware of that function. Thanks!

**Comment by sytolk** [comment]
This is what im talking about. If its have in samples ShotLocationActivity.java extending MainActivity.java with .single() it will save so much time.

**Comment by mcharmas** [comment]
But this is not the responsibility of this library. These feature are really well documented in RxJava docs. Everything that applies to RxJava applies to this library.

**Comment by sytolk** [comment]
Maybe but what to use for one shot location ? .single() or .first()
Its not tested.. If its have example class you and all contributors can choose the best options from RxJava, GMS and plain Android developer can skip reading of RxJava docs with simple copy and paste this usage of library. Think about lazy people ;)

**Comment by sdoward** [comment]
Having looked into this further I think there might be a use case but not in the original way I described.

I have an observable that emits objects potentially every few hours. Once I obtain an object I want to attach a location to it. As these objects are emitted so infrequently I cannot keep the location stream hot as this would cause the app to drain the battery. 

Essentially I would need to request location updates when receiving an emitted item and remove them once a location has been obtained.

**Comment by mcharmas** [comment]
I see. You can easily do that with ```flatMap``` operator.

```java
    public class EmittedObject {
    }

    public class EmittedObjectWithLocation {
        public final EmittedObject emittedObject;
        public final Location location;

        public EmittedObjectWithLocation(EmittedObject emittedObject, Location location) {
            this.emittedObject = emittedObject;
            this.location = location;
        }
    }
    
   Observable<EmittedObjectWithLocation> objectsWithLocation = Observable
                .just(new EmittedObject())
                .flatMap(emittedObject -> locationProvider
                                .getLastKnownLocation()
                                .map(location -> new EmittedObjectWithLocation(emittedObject, location))
                );
```

```Observable.just(new EmittedObject())``` represents you source stream.

You can learn more about flatMap here: http://reactivex.io/documentation/operators/flatmap.html

**Comment by sytolk** [comment]
@mcharmas I`m not sure that this is the place to write code. Maybe in samples this flatMap will looks better..

**Comment by sdoward** [comment]
Yes this works with lastKnown location but I need it with a new locationUpdate

**Comment by mcharmas** [comment]
To be honest I can't spot the difference in usage.


```locationProvider.getLocationUpdates(request).single().map(location -> new EmittedObjectWithLocation(emittedObject, location));````

Or you can use ```firstOrDefault(null)```. Then when stream is empty for some reason you will not get location.
