### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by sibelius** [mcharmas/Android-ReactiveLocation#89]
Probably a memory leak, using [CanaryLeak](https://github.com/square/leakcanary)

```
In com.example:1.5.0:27.
* com.example.ui.record.RecordFragment$5 has leaked:
* GC ROOT com.google.android.gms.location.internal.zzd$zzb.zzakL
* references com.google.android.gms.location.internal.zzd(.zzaLI (anonymous class extends com.google.android.gms.location.internal.zzd$zza)
* references pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable(.val$observer (anonymous class implements com.google.android.gms.location.LocationListener)
* references rx.internal.operators.OperatorMerge$InnerSubscriber.parent
* references rx.internal.operators.OperatorMerge$MergeSubscriber.child
* references rx.observers.SafeSubscriber.actual
* references rx.Observable[8.val$onNext (anonymous class extends rx.Subscriber)
* references com.example.ui.record.RecordFragment[.this$0 (anonymous class implements rx.functions.Action1)
* references com.example.ui.record.RecordFragment.mCounter
* leaks com.example.ui.record.RecordFragment$5 instance (anonymous class extends android.os.CountDownTimer)]]))
```

**Comment by mcharmas** [comment]
Could you provide consumer code that is using the library? RecordFragment?

Do you unsubscribe from observable in proper moment?

**Comment by sibeliusseraphini** [comment]
@mcharmas I did some investigation and the leak is in another part of my code.
Best.

Great library by the way

**Comment by evelyne24** [comment]
This is still happening. To replicate, add a DemoApplication to your sample and enable StrictMode.
Rotate the device a couple of times then dump the Java heap. 

Looking at the .hprof tile, it seems more like a spike leak, the memory is reclaimed but not in time. You'll also see it in StrictMode, 5 instances then 2, if you wait a bit:

05-23 23:21:36.413 13395-13395/pl.charmas.android.reactivelocation.sample E/StrictMode: class pl.charmas.android.reactivelocation.sample.MainActivity; instances=4; limit=1
                                                                                        android.os.StrictMode$InstanceCountViolation: class pl.charmas.android.reactivelocation.sample.MainActivity; instances=4; limit=1
                                                                                            at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
05-23 23:21:37.390 13395-13395/pl.charmas.android.reactivelocation.sample E/StrictMode: class pl.charmas.android.reactivelocation.sample.MainActivity; instances=5; limit=1
                                                                                        android.os.StrictMode$InstanceCountViolation: class pl.charmas.android.reactivelocation.sample.MainActivity; instances=5; limit=1
                                                                                            at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
05-23 23:21:38.044 13395-13395/pl.charmas.android.reactivelocation.sample E/StrictMode: class pl.charmas.android.reactivelocation.sample.MainActivity; instances=2; limit=1
                                                                                        android.os.StrictMode$InstanceCountViolation: class pl.charmas.android.reactivelocation.sample.MainActivity; instances=2; limit=1
                                                                                            at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)

I'm attaching the file, in case you have some time to look over. I'd really appreciate your thoughts on this.
[sample.hprof.zip](https://github.com/mcharmas/Android-ReactiveLocation/files/278394/sample.hprof.zip)

**Comment by mcharmas** [comment]
I'll take a look at it next week. Could you analyze where is the source of this leak using memory analyzer?

**Comment by bellierjonathan** [comment]
I got the same problem :/

**Comment by xbroak** [comment]
Please consider allowing the above pull request!

**Comment by mck182** [comment]
This is unfortunately still an issue today.

The referenced PR does fix it. Any updates on this?
