### ISSUE TITLE
Compilation error in code copied from sample project

### ISSUE THREAD

**Issue by varunachar** [mcharmas/Android-ReactiveLocation#90]
I copied this code from the MainActivity.java class

```java
locationSubscription = locationProvider
                .checkLocationSettings(
                        new LocationSettingsRequest.Builder()
                                .addLocationRequest(request)
                                .setAlwaysShow(true)  //Refrence: http://stackoverflow.com/questions/29824408/google-play-services-locationservices-api-new-option-never
                                .build()
                ).doOnNext(new Action1<LocationSettingsResult>() {
                    @Override
                    public void call(LocationSettingsResult locationSettingsResult) {
                        Status status = locationSettingsResult.getStatus();
                        if (status.getStatusCode() == LocationSettingsStatusCodes.RESOLUTION_REQUIRED) {
                            try {
                                status.startResolutionForResult(MapManager.this.getActivity(), MY_PERMISSIONS_REQUEST_ACCESS_FINE_LOCATION);
                            } catch (IntentSender.SendIntentException th) {
                                Log.e("Map Manager", "Error opening settings activity.", th);
                            }
                        }
                    }
                })
                .flatMap(new Func1<LocationSettingsResult, Observable<Location>>() {
                    @Override
                    public Observable<Location> call(LocationSettingsResult locationSettingsResult) {
                        return locationProvider.getUpdatedLocation(request);
                    }
                });
```

I get the error 

Error:(134, 25) error: incompatible types: no instance(s) of type variable(s) R exist so that Observable<R> conforms to Subscription
where R,T are type-variables:
R extends Object declared in method <R>flatMap(Func1<? super T,? extends Observable<? extends R>>)
T extends Object declared in class Observable

Android studio reports 

<img width="1031" alt="screen shot 2015-11-20 at 11 45 06 pm" src="https://cloud.githubusercontent.com/assets/901108/11307851/d73331a8-8fe0-11e5-8364-85bda691143a.png">

**Comment by mcharmas** [comment]
Hello,
I am afraid that you inaccurately copy-pasted sample code. Please take a look at the type of left side of assign expression on sample code. It is ```Observable<Location> locationUpdatesObservable;```. In your code, deducing from name of your variable ```locationSubscription```, it is probably typed as ```Subscription```. ```Observable``` cannot be assigned to ```Subscription``` variable - this probably causes compilation error.

To transform ```Observable``` to subscription you have to use ```subscribe()``` method. You can check it out in MainActivity - lines 133 - 143 where subscription actually happens. Please do remember to unsubscribe created subscription in for example ```onStop()``` method to avoid memory leaks.

Hopefully that helps.

**Comment by varunachar** [comment]
Hello,

Thanks for pointing that out. You were right. 

Varun

**Comment by varunachar** [comment]
Am I right to assume that the `locationProvider.checkLocationSettings` method automatically checks for ACCESS_FINE_LOCATION and prompts the user?

**Comment by mcharmas** [comment]
No - it does not.
